/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _CLOCK_CONFIG_H_
#define _CLOCK_CONFIG_H_

#include "fsl_common.h"

/*******************************************************************************
 * Definitions
 ******************************************************************************/
#define BOARD_XTAL0_CLK_HZ                         12000000U  /*!< Board xtal0 frequency in Hz */
#define BOARD_XTAL32K_CLK_HZ                          32768U  /*!< Board xtal32K frequency in Hz */

/*******************************************************************************
 ************************ BOARD_InitBootClocks function ************************
 ******************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus*/

/*!
 * @brief This function executes default configuration of clocks.
 *
 */
void BOARD_InitBootClocks(void);

#if defined(__cplusplus)
}
#endif /* __cplusplus*/

/*******************************************************************************
 ******************** Configuration BOARD_BootClockIRC12M **********************
 ******************************************************************************/
/*******************************************************************************
 * Definitions for BOARD_BootClockIRC12M configuration
 ******************************************************************************/
#define BOARD_BOOTCLOCKIRC12M_CORE_CLOCK           12000000U  /*!< Core clock frequency: 12000000Hz */


/* Clock outputs (values are in Hz): */
#define BOARD_BOOTCLOCKIRC12M_ASYNCADC_CLOCK          0UL
#define BOARD_BOOTCLOCKIRC12M_ASYNCAPB_CLOCK          12000000UL
#define BOARD_BOOTCLOCKIRC12M_CLK32K_CLOCK            0UL
#define BOARD_BOOTCLOCKIRC12M_CLKOUT_CLOCK            0UL
#define BOARD_BOOTCLOCKIRC12M_FRG_CLOCK               12000000UL
#define BOARD_BOOTCLOCKIRC12M_MAIN_CLOCK              12000000UL
#define BOARD_BOOTCLOCKIRC12M_SYSTICK_CLOCK           0UL
#define BOARD_BOOTCLOCKIRC12M_SYSTEM_CLOCK            12000000UL
#define BOARD_BOOTCLOCKIRC12M_TRACE_CLOCK             0UL
#define BOARD_BOOTCLOCKIRC12M_WDT_CLOCK               0UL

/*******************************************************************************
 * API for BOARD_BootClockIRC12M configuration
 ******************************************************************************/
#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus*/

/*!
 * @brief This function executes configuration of clocks.
 *
 */
void BOARD_BootClockIRC12M(void);

#if defined(__cplusplus)
}
#endif /* __cplusplus*/

/*******************************************************************************
 ******************** Configuration BOARD_BootClockPLL48M **********************
 ******************************************************************************/
/*******************************************************************************
 * Definitions for BOARD_BootClockPLL48M configuration
 ******************************************************************************/
#define BOARD_BOOTCLOCKPLL48M_CORE_CLOCK           48000000U  /*!< Core clock frequency: 48000000Hz */


/* Clock outputs (values are in Hz): */
#define BOARD_BOOTCLOCKPLL48M_ASYNCADC_CLOCK          0UL
#define BOARD_BOOTCLOCKPLL48M_ASYNCAPB_CLOCK          48000000UL
#define BOARD_BOOTCLOCKPLL48M_CLK32K_CLOCK            0UL
#define BOARD_BOOTCLOCKPLL48M_CLKOUT_CLOCK            0UL
#define BOARD_BOOTCLOCKPLL48M_FRG_CLOCK               48000000UL
#define BOARD_BOOTCLOCKPLL48M_MAIN_CLOCK              48000000UL
#define BOARD_BOOTCLOCKPLL48M_SYSTICK_CLOCK           0UL
#define BOARD_BOOTCLOCKPLL48M_SYSTEM_CLOCK            48000000UL
#define BOARD_BOOTCLOCKPLL48M_TRACE_CLOCK             0UL
#define BOARD_BOOTCLOCKPLL48M_WDT_CLOCK               0UL

/*******************************************************************************
 * API for BOARD_BootClockPLL48M configuration
 ******************************************************************************/
#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus*/

/*!
 * @brief This function executes configuration of clocks.
 *
 */
void BOARD_BootClockPLL48M(void);

#if defined(__cplusplus)
}
#endif /* __cplusplus*/

/*******************************************************************************
 ******************** Configuration BOARD_BootClockPLL96M **********************
 ******************************************************************************/
/*******************************************************************************
 * Definitions for BOARD_BootClockPLL96M configuration
 ******************************************************************************/
#define BOARD_BOOTCLOCKPLL96M_CORE_CLOCK           96000000U  /*!< Core clock frequency: 96000000Hz */


/* Clock outputs (values are in Hz): */
#define BOARD_BOOTCLOCKPLL96M_ASYNCADC_CLOCK          0UL
#define BOARD_BOOTCLOCKPLL96M_ASYNCAPB_CLOCK          96000000UL
#define BOARD_BOOTCLOCKPLL96M_CLK32K_CLOCK            0UL
#define BOARD_BOOTCLOCKPLL96M_CLKOUT_CLOCK            0UL
#define BOARD_BOOTCLOCKPLL96M_FRG_CLOCK               96000000UL
#define BOARD_BOOTCLOCKPLL96M_MAIN_CLOCK              96000000UL
#define BOARD_BOOTCLOCKPLL96M_SYSTICK_CLOCK           0UL
#define BOARD_BOOTCLOCKPLL96M_SYSTEM_CLOCK            96000000UL
#define BOARD_BOOTCLOCKPLL96M_TRACE_CLOCK             0UL
#define BOARD_BOOTCLOCKPLL96M_WDT_CLOCK               0UL

/*******************************************************************************
 * API for BOARD_BootClockPLL96M configuration
 ******************************************************************************/
#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus*/

/*!
 * @brief This function executes configuration of clocks.
 *
 */
void BOARD_BootClockPLL96M(void);

#if defined(__cplusplus)
}
#endif /* __cplusplus*/

/*******************************************************************************
 ******************** Configuration BOARD_BootClockPLL150M *********************
 ******************************************************************************/
/*******************************************************************************
 * Definitions for BOARD_BootClockPLL150M configuration
 ******************************************************************************/
#define BOARD_BOOTCLOCKPLL150M_CORE_CLOCK         150000000U  /*!< Core clock frequency: 150000000Hz */


/* Clock outputs (values are in Hz): */
#define BOARD_BOOTCLOCKPLL150M_ASYNCADC_CLOCK         0UL
#define BOARD_BOOTCLOCKPLL150M_ASYNCAPB_CLOCK         150000000UL
#define BOARD_BOOTCLOCKPLL150M_CLK32K_CLOCK           0UL
#define BOARD_BOOTCLOCKPLL150M_CLKOUT_CLOCK           0UL
#define BOARD_BOOTCLOCKPLL150M_FRG_CLOCK              150000000UL
#define BOARD_BOOTCLOCKPLL150M_MAIN_CLOCK             150000000UL
#define BOARD_BOOTCLOCKPLL150M_SYSTICK_CLOCK          0UL
#define BOARD_BOOTCLOCKPLL150M_SYSTEM_CLOCK           150000000UL
#define BOARD_BOOTCLOCKPLL150M_TRACE_CLOCK            0UL
#define BOARD_BOOTCLOCKPLL150M_WDT_CLOCK              0UL

/*******************************************************************************
 * API for BOARD_BootClockPLL150M configuration
 ******************************************************************************/
#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus*/

/*!
 * @brief This function executes configuration of clocks.
 *
 */
void BOARD_BootClockPLL150M(void);

#if defined(__cplusplus)
}
#endif /* __cplusplus*/

#endif /* _CLOCK_CONFIG_H_ */

